name: MichaelAugsten
favicon: null
layout_spectrum: 1
typography_spectrum: 0.89296
title: Michel Augsten
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-674095-32
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f8f8f7'
    - '#242424'
    - '#d5c5ab'
    - '#e05c62'
    - '#514f40'
  brandStrength: 0.625
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
